#!/bin/sh
# read system info
read -r host < /proc/sys/kernel/hostname
read -r kernel < /proc/sys/kernel/osrelease
pkgs=$(pacman -Qqs | wc -l)
. /etc/os-release

wm='sway'

c0='\e[0m';
c1='\e[31m'; c2='\e[32m'
c3='\e[33m'; c4='\e[34m'
c5='\e[35m'; c6='\e[36m'
c7='\e[37m'; c8='\e[38m'
palette="\e[7m$c1 $c1 $c2 $c2 $c3 $c3 $c4 $c4 $c5 $c5 $c6 $c6 \e[m"

# Output
printf "\n
    ${c5}     .-.         ${USER}${c0}@${c5}${host}
    ${c5}  __/   (        ${c6}os${c0}      ${PRETTY_NAME}
    ${c5}, '-.____\\       ${ARTR3}${c6}kernel${c0}  ${kernel}
    ${c5} u=='/  \\        ${c6}shell${c0}   ${SHELL##*/}
    ${c5}    /_/  \\       ${c6}wm${c0}      ${wm}
    ${c5}  .-''   |       ${c6}pkgs${c0}    ${pkgs}
    ${c5} (  ${c6}____${c5}/${c6}_____   ${palette}\n\n
"

